# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hey
email: luyang(a)whu.edu.cn
description: "God said, 'Let there be light,' and there was light. ---- The First Day."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://MAGI-Yang.github.com" # the base hostname & protocol for your site
twitter_username: MAGI_Yang
github_username:  MAGI-Yang

# Build settings
markdown: kramdown
